### ISSUE TITLE
Error in viaf_suggest

### ISSUE THREAD

**Issue by solaresig** [stefanieschneider/viafr#1]
Hello I am new to the use of the API of viaf

Some searches give the following error. Here is an example

viaf_suggest("BESSHI COPPER MINE")
Error: Problem with `mutate()` input `source_ids`.
x Input `source_ids` can't be recycled to size 1.
i Input `source_ids` is `map(...)`.
i Input `source_ids` must be size 1, not 0.
Run `rlang::last_error()` to see where the error occurred.

I tried with both the cran and the github version of viafr

Thank you

**Comment by stefanieschneider** [comment]
Hi @solaresig, thanks for your bug report. This should now be fixed in development.
