### ISSUE TITLE
Mistaken pull request

### ISSUE THREAD

**Issue by AlanInTsukuba** [stefanieschneider/viafr#3]
Stephanie,

Thank you for creating viafr.

A few weeks ago I forked it and have been working on extensions for the purpose of extracting viafID pairs for coauthors. I have made one semi-successful pass through the process and am now reworking the functions.

At some time I hope to submit it to you for consideration. But I inadvertantly submitted a pull request that isn't ready yet. Please refuse it.

Thank you.
Alan

**Comment by stefanieschneider** [comment]
Hi Alan,

Thanks for your input and for letting me know about the pull request. Whenever you're ready with the updates and feel confident with the new features, feel free to submit a new pull request for review.

Let me know if you need any help or feedback on your work!
